apiVersion: v1
kind: Pod
metadata:
  name: rastreio-correios
spec:
  containers:
  - name: rastreio-correios
    image: lyamadadocker/docker-rastreio-correios:v1
    imagePullPolicy: Always
    envFrom:
        - configMapRef:
            name: rastreio-config
    resources:
        limits:
            memory: "256Mi"
            cpu: "200m"
        requests:
            memory: "128Mi"
            cpu: "50m"
  restartPolicy: Never